---
# defaults file for mbed-dev
mbed_source_dir: "~/Source/"
mbed_repo_name: "mbed-cloud-client-example"
mbed_repo_url: "https://github.com/ARMmbed/{{ mbed_repo_name }}"
mbed_cli: "/usr/local/bin/mbed"